# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grumbar.me
# email: harry@grumbar.me
# description: > # this means to ignore newlines until "baseurl:"
#  This is just a holding page for the grumbar.me domain. There's nothing to see here.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://grumbar.me" # the base hostname & protocol for your site
# twitter_username: harrygrumbar
# github_username:  harrygr

# Build settings
markdown: kramdown
